### ISSUE TITLE
Extension for automatic output filename

### ISSUE THREAD

**Issue by markus-stoll** [CognitionGuidedSurgery/msml#185]
The current automatic filename generation does not add an extension to the output. But that is needed as following operators need this information to select the proper reader via IOHelper. The same is true for the user... e.g. with paraview

Any ideas?

**Comment by markus-stoll** [comment]
can we close this issue?

**Comment by areku** [comment]
I make a fix, but does it work for you?

The fix is a workaround: I use the physical sort name as the suffix.
