### ISSUE TITLE
Update variable functionality broken in SimulationRunner

### ISSUE THREAD

**Issue by uiccg** [CognitionGuidedSurgery/msml#206]
e.g. in Beam/runner_test.py

**Comment by ssuwelack** [comment]
Here is how i tested the Beam/runner_test.py:
- in the original file beamLineradDisp.msml.xml the dispVar is set to 0.1
- in the python script the variable is set to 1.0
- in the output .scn (/tmp/MSMLResults/beamLinearDisp.msml.scn) the displacement (located as parameter movements in LinearMovementConstraint) is still 0.1 

Can you reproduce that?
