### ISSUE TITLE
Support for multiple outputs in scene

### ISSUE THREAD

**Issue by dschauba** [CognitionGuidedSurgery/msml#209]
I will start implementation of support for multiple outputs in Scene/MSMLFile.
Currently, only one output per scene seems to be supported, right?

Since scenes i create feature multiple objects, support for multiple (distinguishable) output is necessary.

_output Member of SceneObjects seems to be a list already.

**Comment by areku** [comment]
No. 
The scene does not have any outputs. 
SceneObject has multiple Output(-Request), but currently no exporters uses this. 

The exporter (`gather_outputs`) generates a unique name for every output request.

**Comment by dschauba** [comment]
Ok, thanks for clarification!

Looking add how output requests are created in sofa-exporter, i noticed that output requests get overidden.
See (sofanew.py, line: 633ff):
```python
if _bool(request.useAsterisk):  #TODO: et_value_from_memory(request, 'useAsterisk')
    self._memory_update[self.id] = {request.id: VTK(str(filename + '*' + ".vtu"))}
else:
    self._memory_update[self.id] = {request.id: VTK(str(filename + str(lastNumber) + ".vtu"))}
```
Now, if have multiple objects in scene, only the last object in scene definition will get an entry in memory. All previous commits to memory are overriden.
I extended this to:
```python
if _bool(request.useAsterisk):  #TODO: et_value_from_memory(request, 'useAsterisk')
    self._memory_update[self.id] = {request.id: VTK(str(filename + '*' + ".vtu"))}
else:
    if(self.id not in self._memory_update):
        self._memory_update[self.id] = {request.id: VTK(str(filename + str(lastNumber) + ".vtu"))}
    else:
        self._memory_update[self.id].update({request.id: VTK(str(filename + str(lastNumber) + ".vtu"))})
```

So, all output requests will be collected in __exporter__ key/value pair in memory.
(Not taking variadics into account....)

**Comment by areku** [comment]
An shorter version would be

```
self._memory_update={self.id : {}}
```

as initialization and then you can always set the output directly.

```
self._memory_update[self.id][request.id] = VTK("%s%d.vtu" % (filename, lastNumber)) 
```

**Comment by dschauba** [comment]
Thanks, much nicer!

**Comment by markus-stoll** [comment]
Can we have it also for the useAsterisk block ?

**Comment by dschauba** [comment]
Sure, now also available for useAsterisk.
see: https://github.com/CognitionGuidedSurgery/msml/commit/5fbad675943b073908464e5f5d434d35627c66b9

**Comment by dschauba** [comment]
Seems to work fine, so i´m closing this issue.
