### ISSUE TITLE
nose test fails with segfault

### ISSUE THREAD

**Issue by dschauba** [CognitionGuidedSurgery/msml#211]
Currently, nose test of LungsTest fails with a segfault of vtk.
(https://circleci.com/gh/CognitionGuidedSurgery/msml/423)
```
test_Lung (msmltest.LungsTest) ... ERROR: In /home/ubuntu/msml/cache/VTK-6.1.0/Common/ExecutionModel/vtkDemandDrivenPipeline.cxx, line 715
vtkCompositeDataPipeline (0x2eaa910): Input port 0 of algorithm vtkUnstructuredGridGeometryFilter(0x38ead40) has 0 connections but is not optional.

share/run_test.sh: line 14: 26169 Segmentation fault      (core dumped) nosetests -vv --with-coverage --cover-tests --cover-inclusive --cover-package=msml --cover-erase -w src msmltest
```

**Comment by markus-stoll** [comment]
I guess it is a problem with asteriks in sofa exporter

**Comment by dschauba** [comment]
Not sure, Lungs_simple (which is used in LungsTest) does not use asterisk.
Lungs_new_wild does use asterisk.

Both work locally.

**Comment by dschauba** [comment]
Ah, damn.
Reason propably is that i changed call arguments of sofa in sofanew!
So sofa is not called correctly on circle ci and postprocessing does not get appropriate input data, i suppose.
see: https://github.com/CognitionGuidedSurgery/msml/commit/432b83f0d28ce2202371b4e68f97676b2537f4b7

**Comment by markus-stoll** [comment]
can you please fix it and remove my tmp branch afterwards ? :)

**Comment by dschauba** [comment]
Right, of course ;)
