### ISSUE TITLE
CMake warnings in current experimental version

### ISSUE THREAD

**Issue by markus-stoll** [CognitionGuidedSurgery/msml#213]
#############################
 # CMAKE BUILD TYPE = Release
 #############################
Boost version: 1.55.0
Found the following Boost libraries:
  program_options
  unit_test_framework
  filesystem
  iostreams
  regex
  system
  iostreams
Found PythonLibs: C:/dev/Python27/libs/python27.lib
Base: ENABLED and ACTIVE
CMake Warning (dev) at CMakeLists.txt:202 (GET_TARGET_PROPERTY):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "Base".  Use the
  target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

Call Stack (most recent call first):
  Base/CMakeLists.txt:28 (MSML_LIBRARY)
This warning is for project developers.  Use -Wno-dev to suppress it.

C:/dev/msml/operators/bin_2010/bin/RELEASE/Base.dll looking for DEPENDENCIES... 
warning: target 'C:/dev/msml/operators/bin_2010/bin/RELEASE/Base.dll' does not exist...
TetgenOperators: ENABLED and ACTIVE
CMake Warning (dev) at CMakeLists.txt:202 (GET_TARGET_PROPERTY):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "TetgenOperators".
  Use the target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

Call Stack (most recent call first):
  TetgenOperators/CMakeLists.txt:48 (MSML_LIBRARY)
This warning is for project developers.  Use -Wno-dev to suppress it.

C:/dev/msml/operators/bin_2010/bin/RELEASE/TetgenOperators.dll looking for DEPENDENCIES... 
warning: target 'C:/dev/msml/operators/bin_2010/bin/RELEASE/TetgenOperators.dll' does not exist...
VCGOperators disabled
MiscMeshOperators: ENABLED and ACTIVE
CMake Warning (dev) at CMakeLists.txt:202 (GET_TARGET_PROPERTY):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "MiscMeshOperators".
  Use the target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

Call Stack (most recent call first):
  MiscMeshOperators/CMakeLists.txt:72 (MSML_LIBRARY)
This warning is for project developers.  Use -Wno-dev to suppress it.

C:/dev/msml/operators/bin_2010/bin/RELEASE/MiscMeshOperators.dll looking for DEPENDENCIES... 
warning: target 'C:/dev/msml/operators/bin_2010/bin/RELEASE/MiscMeshOperators.dll' does not exist...
Boost version: 1.55.0
CGALOperators: ENABLED and ACTIVE
Build type: Release
USING CXXFLAGS = ' /DWIN32 /D_WINDOWS /W3 /GR /EHsc -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_WARNINGS /fp:strict /fp:except- /wd4503 /bigobj /MP  /MD /O2 /Ob2 /D NDEBUG'
USING EXEFLAGS = ' /machine:x64   /INCREMENTAL:NO'
Targetting Visual Studio 10 2010 Win64
Target build enviroment supports auto-linking
Using VC10 compiler.
Generator uses intermediate configuration directory: $(Configuration)
Requested component: Core
Requested component: ImageIO
Could NOT find ZLIB (missing:  ZLIB_LIBRARY ZLIB_INCLUDE_DIR) 
Requested component: MPFR
Requested component: GMP
CMake Warning (dev) at CMakeLists.txt:202 (GET_TARGET_PROPERTY):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "CGALOperators".  Use
  the target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

Call Stack (most recent call first):
  CGALOperators/CMakeLists.txt:75 (MSML_LIBRARY)
This warning is for project developers.  Use -Wno-dev to suppress it.

C:/dev/msml/operators/bin_2010/bin/RELEASE/CGALOperators.dll looking for DEPENDENCIES... 
warning: target 'C:/dev/msml/operators/bin_2010/bin/RELEASE/CGALOperators.dll' does not exist...
MiscExtOperators disabled
Configuring done
Generating done

**Comment by areku** [comment]
Can not confirm on Linux in f48e40d73ba5b2a475c38ad0c570c359bc085aa1 with `cmake version 2.8.12.2`

**Comment by markus-stoll** [comment]
Checkout 3.0.2 or newer

**Comment by areku** [comment]
Can not confirm with 3.1 ether.

```
cbuild git:(experimental) ✗ ~/workspace/cmake-3.1.0-Linux-x86_64/bin/cmake .
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
 #############################
 # CMAKE BUILD TYPE = Release
 #############################
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   program_options
--   unit_test_framework
--   filesystem
--   iostreams
--   regex
--   system
--   iostreams
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found version "2.7.6") 
Base: ENABLED and ACTIVE
TetgenOperators: ENABLED and ACTIVE
VCGOperators: ENABLED and ACTIVE
VCG install dir is /home/weigl/workspace/msml/cbuild/VCGOperators/vcg
MiscMeshOperators: ENABLED and ACTIVE
-- Boost version: 1.54.0
CGALOperators: ENABLED and ACTIVE
-- Build type: Release
-- USING CXXFLAGS = '-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2  -frounding-math  -Wno-deprecated -O3 -DNDEBUG'
-- USING EXEFLAGS = ' -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed  '
-- Targetting Unix Makefiles
-- Using /usr/bin/c++ compiler.
-- Requested component: Core
-- Requested component: ImageIO
-- Requested component: MPFR
-- Requested component: GMP
ACVD as external project
ACVDOperators: ENABLED and ACTIVE
ACVD include are /home/weigl/workspace/msml/cbuild/ACVDOperators/acvd/src/ACVD/vtkDiscreteRemeshing/;/home/weigl/workspace/msml/cbuild/ACVDOperators/acvd/src/ACVD/vtkSurface/;/home/weigl/workspace/msml/cbuild/ACVDOperators/acvd/src/ACVD/vtkVolumeProcessing/;/home/weigl/workspace/msml/cbuild/ACVDOperators/acvd/src/ACVD/DiscreteRemeshing/;/home/weigl/workspace/msml/cbuild/ACVDOperators/acvd/src/ACVD/Common/;/home/weigl/workspace/msml/cbuild/ACVDOperators/acvd/src/ACVD/VolumeProcessing/
-- Configuring done
-- Generating done
-- Build files have been written to: /home/weigl/workspace/msml/cbuild
➜  cbuild git:(experimental) ✗ 
```

**Comment by markus-stoll** [comment]
Then I guess CMP0026 is set on your system to use old CMake behavior- do we really need that? Than we maybe we can add CMP0026  to our CMake files.

http://www.cmake.org/cmake/help/v3.0/policy/CMP0026.html

**Comment by markus-stoll** [comment]
fixed with removal of CPack and install macros from CMakeList.txt
