### ISSUE TITLE
Possible Issues with multiple meshes, wrong slot name

### ISSUE THREAD

**Issue by areku** [CognitionGuidedSurgery/msml#223]
In [`exporter/base.py`](https://github.com/CognitionGuidedSurgery/msml/blob/master/src/msml/exporter/base.py#L218) Line 218: **Should** use the common function `self.get_input_mesh_name(mesh_object)` to get the unique string for slot name of a mesh object.

Current implementation diverges in the slot name between retrieve of values of the given mesh file in [`self.get_value_from_memory(obj)`](https://github.com/CognitionGuidedSurgery/msml/blob/master/src/msml/exporter/base.py#L345) and the declaration of the slot name.

@dschauba  I assigned you, because a fix would effect your code, that I can not test.

The fix is the replacement of:
```
 mesh_exporter_id = (scene_obj.id + '_mesh') 
```
with 
```
mesh_exporter_id = self.get_input_mesh_name(scene_obj.mesh) 
```

**Comment by dschauba** [comment]
OK, will do!

**Comment by dschauba** [comment]
Yeah, looking good! SOFA scn-File is as expected after fix.

**Comment by markus-stoll** [comment]
fixed?

**Comment by dschauba** [comment]
Should be fixed, close?
