### ISSUE TITLE
Problem using scipy optimizer and variadic arguments

### ISSUE THREAD

**Issue by dschauba** [CognitionGuidedSurgery/msml#224]
Variadic arguments again ;)

Using one of the optimizers provided in scipy, and a workflow containing Operators with variadic arguments, execution of this operator is aborted/hangs.
Execution stops with this line.
```python
INFO     Executing operator of task <Task bary (TransformMeshBarycentric)> with arguments {'targetVolumeMesh': 'deformed_tumor_meshes*.vtk', 'volumeMeshToDeform': 'tumor_extract.vtk', 'deformedVolumeMesh': 'movingMeshA*.vtu', 'referenceVolumeMesh': 'moving_fem_split.vtk'}
```

Removing the TransformMeshBarycentric-Operator from workflow fixes the problem. 

So i guess it has something to do with parallel execution of tasks from within scipy-optimizer function 
(the MSML-Workflow is started from within the function to optimize!)

Is scipy somehow using and holding the GIL?

**Comment by areku** [comment]
I think a good starting point is to enrich the logging in the used operator.

You can get the process name with:
```
cpname = multiprocessing.current_process().name
```
or [getpid](http://pubs.opengroup.org/onlinepubs/009695399/functions/getpid.html) in C/C++.

Additionally you can write a new C++ function in the swig-wrapper, that release and locks the GIL.
https://docs.python.org/2/c-api/init.html#releasing-the-gil-from-extension-code

```c++
std::string TransformMeshBarycentricGIL(const char* meshPath, const char* referenceGridPath, const char* deformedGridPath, const char* outMeshPath, float interpolateOutsideDistance){
  Py_BEGIN_ALLOW_THREADS
  
  std::string tmp = TransformMeshBarycentric(meshPath, referenceGridPath, deformedGridPath, outMeshPath, interpolateOutsideDistance);

  Py_END_ALLOW_THREADS
  return tmp;
}
```

**Comment by markus-stoll** [comment]
did you use 
if __name__ == '__main__':

in your main python method?

**Comment by dschauba** [comment]
Nice!
Doing just as Markus said helped!
Totally forgot about this ;)

Thanks to both of you!
