### ISSUE TITLE
Empty, None, Default Exporter

### ISSUE THREAD

**Issue by dschauba** [CognitionGuidedSurgery/msml#225]
Would it make any sense having a default exporter, which does nothing?
I have some workflows which do not need an exporter (no simulation, just processing of meshes).

Having a default exporter would be "cleaner" than having to include an environment-definition in workflow xml-file (since SOFA-Exporter seems to be the default exporter).

**Comment by areku** [comment]
The `msml.model.base.Exporter` ist an empty exporter, that does nothing. 
You can specify it with `-e base`

**Comment by dschauba** [comment]
Thanks!
