### ISSUE TITLE
Operators with more than two variadic arguments

### ISSUE THREAD

**Issue by dschauba** [CognitionGuidedSurgery/msml#227]
I would like to implement support for operators with more than two variadic arguments.
Until now, only operators with one variadic input argument and one output argment seem to be supported.
One operator i implemented features two possibly variadic input arguments and one output argument (also variadic in my workflow).

How to determine pattern for output path? 
Should i force consistency in input pattern of argument A and B ? 
In msml/model/sequence.py output pattern is determined from input pattern.

Best method would be to enforce consistency in pattern of input arguments and just apply this pattern to output argument(s), right?

**Comment by areku** [comment]
I have notes on my desk to enhanced the operator system by automatically "lifting".
A operator `f( a : VTK, b : VTK, c : int)  : VTK` would become `f( a : List[VTK], b : List[VTK], c : int)  : List[VTK]` if ether `a` or `b` is a list. 
`List[T]` is a sort, that is equally defined as physical and logical similar to `T`.

For now, the "sequence" is a big bad workaround.

**Comment by dschauba** [comment]
Sounds great! 
At the moment, some parts of my workflow (some post processing stuff) are done in python scripts, because of missing support for more than two variadic arguments.
So this would be a fantastic think to have ;).

**Comment by markus-stoll** [comment]
Is anyone working on it?

**Comment by areku** [comment]
The changes are deep:

* Sorts like `List[VTK/Mesh]` are possible
  * Maybe we need to allow sorts of `List[List[int]]` 
* Task sorts can differ from operator sorts
* Changes in building of the DAG and Executor

It is not a small change.

**Comment by markus-stoll** [comment]
Workaround: until the deep changes are done: For 3 varadic args python scripts are being used instead of a msml workflow.

**Comment by markus-stoll** [comment]
Curren chosen quick and dirty solution: Use scripting :)
"Deep changes" should be done in MSML 2.0
