### ISSUE TITLE
Operator Build Error

### ISSUE THREAD

**Issue by SarahGrimm** [CognitionGuidedSurgery/msml#228]
Can't build cause of error C2440: 'Initialisierung': 'vtkUnstructuredGridBase *' kann nicht in 'vtkUnstructuredGrid *' konvertiert werden.

1>------ Erstellen gestartet: Projekt: ZERO_CHECK, Konfiguration: Release x64 ------
1>Der Buildvorgang wurde am 02.04.2015 13:22:08 gestartet.
1>InitializeBuildStatus:
1>  "x64\Release\ZERO_CHECK\ZERO_CHECK.unsuccessfulbuild" wird erstellt, da "AlwaysCreate" angegeben wurde.
1>FinalizeBuildStatus:
1>  Die Datei "x64\Release\ZERO_CHECK\ZERO_CHECK.unsuccessfulbuild" wird gelöscht.
1>  Aktualisieren des Timestamps von "x64\Release\ZERO_CHECK\ZERO_CHECK.lastbuildstate".
1>
1>Das Erstellen war erfolgreich.
1>
1>Verstrichene Zeit 00:00:00.09
2>------ Erstellen gestartet: Projekt: MiscMeshOperators, Konfiguration: Release x64 ------
2>Der Buildvorgang wurde am 02.04.2015 13:22:08 gestartet.
2>InitializeBuildStatus:
2>  Aktualisieren des Timestamps von "MiscMeshOperators.dir\Release\MiscMeshOperators.unsuccessfulbuild".
2>CustomBuild:
2>  Alle Ausgaben sind aktuell.
2>ClCompile:
2>  MiscMeshOperators.cpp
2>  PostProcessingOperators.cpp
2>..\..\MiscMeshOperators\MiscMeshOperators.cpp(401): warning C4267: 'Initialisierung': Konvertierung von 'size_t' nach 'int', Datenverlust möglich
2>..\..\MiscMeshOperators\MiscMeshOperators.cpp(520): warning C4267: 'Initialisierung': Konvertierung von 'size_t' nach 'int', Datenverlust möglich
2>..\..\MiscMeshOperators\MiscMeshOperators.cpp(935): error C2440: 'Initialisierung': 'vtkUnstructuredGridBase *' kann nicht in 'vtkUnstructuredGrid *' konvertiert werden
2>          Umwandlung von der Basis in die Ableitung erfordert 'dynamic_cast' oder 'static_cast'
2>..\..\MiscMeshOperators\MiscMeshOperators.cpp(979): warning C4267: 'Initialisierung': Konvertierung von 'size_t' nach 'unsigned int', Datenverlust möglich
2>..\..\MiscMeshOperators\MiscMeshOperators.cpp(1039): error C2440: 'Initialisierung': 'vtkUnstructuredGridBase *' kann nicht in 'vtkUnstructuredGrid *' konvertiert werden
2>          Umwandlung von der Basis in die Ableitung erfordert 'dynamic_cast' oder 'static_cast'
2>..\..\MiscMeshOperators\MiscMeshOperators.cpp(1043): warning C4267: 'Initialisierung': Konvertierung von 'size_t' nach 'unsigned int', Datenverlust möglich
2>..\..\MiscMeshOperators\MiscMeshOperators.cpp(1705): error C2440: 'Initialisierung': 'vtkUnstructuredGridBase *' kann nicht in 'vtkUnstructuredGrid *' konvertiert werden
2>          Umwandlung von der Basis in die Ableitung erfordert 'dynamic_cast' oder 'static_cast'
2>..\..\MiscMeshOperators\MiscMeshOperators.cpp(1773): warning C4018: '<': Konflikt zwischen 'signed' und 'unsigned'
2>..\..\MiscMeshOperators\MiscMeshOperators.cpp(1807): warning C4267: 'Initialisierung': Konvertierung von 'size_t' nach 'unsigned int', Datenverlust möglich
2>..\..\MiscMeshOperators\MiscMeshOperators.cpp(1818): warning C4018: '<': Konflikt zwischen 'signed' und 'unsigned'
2>..\..\MiscMeshOperators\PostProcessingOperators.cpp(241): warning C4267: 'Initialisierung': Konvertierung von 'size_t' nach 'unsigned int', Datenverlust möglich
2>..\..\MiscMeshOperators\PostProcessingOperators.cpp(242): warning C4267: 'Initialisierung': Konvertierung von 'size_t' nach 'unsigned int', Datenverlust möglich
2>..\..\MiscMeshOperators\PostProcessingOperators.cpp(247): warning C4018: '<': Konflikt zwischen 'signed' und 'unsigned'
2>..\..\MiscMeshOperators\PostProcessingOperators.cpp(345): error C2440: 'Initialisierung': 'vtkUnstructuredGridBase *' kann nicht in 'vtkUnstructuredGrid *' konvertiert werden
2>          Umwandlung von der Basis in die Ableitung erfordert 'dynamic_cast' oder 'static_cast'
2>..\..\MiscMeshOperators\PostProcessingOperators.cpp(1006): warning C4267: 'Initialisierung': Konvertierung von 'size_t' nach 'int', Datenverlust möglich
2>
2>Fehler beim Erstellen
2>
2>Verstrichene Zeit 00:00:23.14
========== Erstellen: 1 erfolgreich, Fehler bei 1, 0 aktuell, 0 übersprungen ==========

**Comment by markus-stoll** [comment]
fixed with 06694d99ad7bf3a439a5397148f533b93fe96391
