### ISSUE TITLE
Operators not found

### ISSUE THREAD

**Issue by SarahGrimm** [CognitionGuidedSurgery/msml#229]
binary_search_path.extend(default_package.full_binary_dir()) 

Uses ':' instead of ';' to separate directories of packages binaries.

**Comment by markus-stoll** [comment]
There sees to be something seriously wrong with CMake and package mechanisms (win7 only). A setup from scratch was not possible for the current experimental branch on different PCs. 

Multiple reasons seem to cause this problem - maybe we can adress it on the hackfest? For now we use the experimental_win_ok branch for setting up new MSML clients.

**Comment by areku** [comment]
The binary search path is only used for operators from executable (like CLI). 
If operators are not found we have to decide if the operator is unknown in a workflow (alphabet path) or the implementation in Python (`sys.path`).

**Comment by markus-stoll** [comment]
Seems to be fixed -  Is anyone still having trouble?
