### ISSUE TITLE
CGALOperators build fails: No execinfo.h

### ISSUE THREAD

**Issue by dschauba** [CognitionGuidedSurgery/msml#231]
Build of CGALOperators fails using VS, since execinfo.h does not exist. This is used in stacktrace.h. 
Just deleting stacktrace.h, and the include in CGALOperators.cpp fixes the problem.

I´m sure you already know of this problem. ;)

**Comment by markus-stoll** [comment]
ahhh we had the ame problem. can you push the fix please?

**Comment by dschauba** [comment]
Okay, just removed the include of stacktrace.h.
(Perhaps add switch to detect if compiler is GCC, since GCC knows of execinfo.h)
