### ISSUE TITLE
IOHelper requires gunzip for gz-ed files

### ISSUE THREAD

**Issue by dschauba** [CognitionGuidedSurgery/msml#232]
It should be noted somewhere that IOHelper will require gunzip (somewhere on PATH) if compressed files are opened in an operator.

**Comment by markus-stoll** [comment]
remark: gunzip is only needed for dkfz internal data (ctx.gz)

**Comment by dschauba** [comment]
Okay, regarding your remark: Would it still make sense to add an option in cmake to pull gunzip from somewhere on the net, if needed (if compressed data is to be processed)?

**Comment by areku** [comment]
Python has gunzip built-in. On Linux platforms gunzip is default package. 
Am I right that this is not a build dependency? 
Then gunzip is a normal program that could obtain somewhere else, or we built in gz support in IOHelpers via zlib.

**Comment by markus-stoll** [comment]
Gunzip is only needed for using data (ctx.gz images) from our radiation therapy (RT) department. I have put it into our DKFZ MSML GIT repository. This makes sense because there are more command line tools needed to use RT data (like the MSML Operator VDX2CTX.exe), which are also located there.

**Comment by areku** [comment]
Then, I'd say this isn't an issues for MSML directly.

**Comment by markus-stoll** [comment]
yes
