### ISSUE TITLE
SOFA does not write into network drive

### ISSUE THREAD

**Issue by markus-stoll** [CognitionGuidedSurgery/msml#237]
If an output directory for an MSML simulation run is defined on a net work drive, the SOFA framework does not write the .vtu output files.

**Comment by markus-stoll** [comment]
e.g. ```python src\msml.py exec \\eXXXX-pcYYY\EZZZ\MSML\examples\CGALPelvis_DKFZ\pelvisCase_new.xml -e nsofa -o tmp```

**Comment by areku** [comment]
As a workaround you could mount the network path (UNC name) to a drive letter.

**Comment by markus-stoll** [comment]
Sofa specific I guess --- yes mounting helps
