### ISSUE TITLE
VCGOperators build error

### ISSUE THREAD

**Issue by markus-stoll** [CognitionGuidedSurgery/msml#239]
/usr/include/c++/4.6/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the upcoming ISO C++ standard, C++0x. This support is currently experimental, and must be enabled with the -std=c++0x or -std=gnu++0x compiler options.

**Comment by areku** [comment]
Options:
a) Upgrade your compiler and enable c++11
b) pin the revision of VCG to an old but working version (there is an option in `ExternalProject_Add` for this)

**Comment by markus-stoll** [comment]
fixed with b) - VCG is now pinned (frozen)
04872a2b59502dc87d9c74bba5ba763939968c59
